openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API for the RAG Chatbot service that connects frontend and backend
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server
paths:
  /api/v1/chat:
    post:
      summary: Send a message to the RAG chatbot and receive a response
      description: Submit a user message to the RAG agent service and receive a contextually relevant response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the RAG agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Chat
  /health:
    get:
      summary: Health check endpoint
      description: Check if the service is running and healthy
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
      tags:
        - Health
components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's message or question
          example: "What are the key concepts in the book?"
        session_id:
          type: string
          description: Session identifier for conversation context (optional)
          format: uuid
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        user_preferences:
          type: object
          description: User preferences for the response (optional)
          properties:
            response_style:
              type: string
              enum: [concise, detailed, balanced]
              default: balanced
    ChatResponse:
      type: object
      required:
        - response
        - sources
        - confidence
        - timestamp
      properties:
        response:
          type: string
          description: The assistant's response to the user's message
          example: "The key concepts in the book include..."
        session_id:
          type: string
          description: The session identifier
          format: uuid
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        sources:
          type: array
          description: List of sources cited in the response
          items:
            type: string
            example: "https://example.com/book/chapter1"
        confidence:
          type: number
          description: Confidence score for the response (0-1)
          format: float
          minimum: 0
          maximum: 1
          example: 0.85
        timestamp:
          type: string
          description: ISO timestamp of the response
          format: date-time
          example: "2025-12-20T10:00:00Z"
        retrieved_chunks:
          type: array
          description: Content chunks used to generate the response
          items:
            $ref: '#/components/schemas/RetrievedChunk'
    RetrievedChunk:
      type: object
      required:
        - id
        - content
        - similarity_score
      properties:
        id:
          type: string
          description: Unique identifier for the chunk
          example: "chunk-123"
        content:
          type: string
          description: The actual content text
          example: "This is a relevant excerpt from the book..."
        similarity_score:
          type: number
          description: Similarity score between 0 and 1
          format: float
          minimum: 0
          maximum: 1
          example: 0.92
        metadata:
          type: object
          description: Additional metadata about the chunk
          properties:
            url:
              type: string
              example: "https://example.com/book/chapter1"
            title:
              type: string
              example: "Chapter 1: Introduction"
            section:
              type: string
              example: "Section 1.1"
    ErrorResponse:
      type: object
      required:
        - error
        - timestamp
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid request format"
        timestamp:
          type: string
          description: ISO timestamp of the error
          format: date-time
          example: "2025-12-20T10:00:00Z"
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          description: Health status
          enum: [healthy]
          example: "healthy"
tags:
  - name: Chat
    description: Chatbot interaction endpoints
  - name: Health
    description: Service health check endpoints